;; generated from
;; guix environment guix --pure --ad-hoc help2man git strace autoconf automake gettext texinfo graphviz guile-ssh guile-zstd guile-semver guile-lib libgcrypt sqlite gcc-toolchain
;; ./pre-inst-env guix package --export-manifest -p $GUIX_ENVIRONMENT/
;; and edited afterwards.

(specifications->manifest
 (list
  "gcc-toolchain"
  "sqlite"
  "libgcrypt"
  "guile-lib"
  "guile-semver"
  "guile-zstd"
  "guile-ssh"
  "graphviz"
  "texinfo"
  "gettext"
  "automake"
  "autoconf"
  "strace"
  "git"
  "help2man"
  "pkg-config"
  "guile"
  "gnutls"
  "guile-avahi"
  "guile-gcrypt"
  "guile-json"
  "guile-sqlite3"
  "guile-zlib"
  "guile-lzlib"
  "guile-git"
  "autoconf"
  "automake"
  "gettext-minimal"
  "po4a"
  "bzip2"
  "gzip"
  "sqlite"
  "util-linux"
  "disarchive"
  ;; "glibc-utf8-locales"
  "tar"
  "gzip"
  "bzip2"
  "xz"
  "file"
  "diffutils"
  "patch"
  "findutils"
  "gawk"
  "sed"
  "grep"
  "coreutils"
  "make"
  "bash-minimal"
  "ld-wrapper"
  "binutils"
  ;; "gcc"
  "glibc"
  "glibc:static"
  ;; "glibc-utf8-locales"
  "libunistring"
  ;; "libgc"
  "zlib"
  "nettle"
  "libidn2"
  "libtasn1"
  "guile-bytestructures"
  "libgpg-error"
  ;; "linux-libre-headers"
  "gmp"))
